[package]
name = "d8p2"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.94"
derive_more = { version = "1.0.0", features = ["from", "mul", "add"] }
itertools = "0.13.0"
memoize = "0.4.2"
num = "0.4.3"
rayon = "1.10.0"
