[package]
name = "d23"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "d23p1"
path = "src/p1.rs"

[[bin]]
name = "d23p2"
path = "src/p2.rs"

[dependencies]
itertools = "0.13.0"
petgraph = "0.6.5"
rustc-hash = "2.1.0"
