[package]
name = "d14"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "d14p1"
path = "src/p1.rs"

[[bin]]
name = "d14p2"
path = "src/p2.rs"

[dependencies]
derive_more = { version = "1.0.0", features = ["add", "constructor", "mul"] }
itertools = "0.13.0"
regex = "1.11.1"
