[package]
name = "d22"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "d22p1"
path = "src/p1.rs"

[[bin]]
name = "d22p2"
path = "src/p2.rs"

[dependencies]
itertools = "0.13.0"
rayon = "1.10.0"
rustc-hash = "2.1.0"
