[package]
name = "d21"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.13.0"
rustc-hash = "2.1.0"


[[bin]]
name = "d21p1"
path = "src/p1.rs"

[[bin]]
name = "d21p2"
path = "src/p2.rs"
